package com.zs.aidata.core.sys.mytest.vo;

import java.util.Date;

public class CoreSysTestDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.id
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.cmf_1
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private String cmf1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.cmf_2
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private String cmf2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.cmf_3
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private String cmf3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.cmf_4
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private String cmf4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.cmf_5
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private String cmf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.date_1
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private Date date1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.date_2
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private Date date2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_sys_test.date_3
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    private Date date3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.id
     *
     * @return the value of t_core_sys_test.id
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.id
     *
     * @param id the value for t_core_sys_test.id
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.cmf_1
     *
     * @return the value of t_core_sys_test.cmf_1
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public String getCmf1() {
        return cmf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.cmf_1
     *
     * @param cmf1 the value for t_core_sys_test.cmf_1
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setCmf1(String cmf1) {
        this.cmf1 = cmf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.cmf_2
     *
     * @return the value of t_core_sys_test.cmf_2
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public String getCmf2() {
        return cmf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.cmf_2
     *
     * @param cmf2 the value for t_core_sys_test.cmf_2
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setCmf2(String cmf2) {
        this.cmf2 = cmf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.cmf_3
     *
     * @return the value of t_core_sys_test.cmf_3
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public String getCmf3() {
        return cmf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.cmf_3
     *
     * @param cmf3 the value for t_core_sys_test.cmf_3
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setCmf3(String cmf3) {
        this.cmf3 = cmf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.cmf_4
     *
     * @return the value of t_core_sys_test.cmf_4
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public String getCmf4() {
        return cmf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.cmf_4
     *
     * @param cmf4 the value for t_core_sys_test.cmf_4
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setCmf4(String cmf4) {
        this.cmf4 = cmf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.cmf_5
     *
     * @return the value of t_core_sys_test.cmf_5
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public String getCmf5() {
        return cmf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.cmf_5
     *
     * @param cmf5 the value for t_core_sys_test.cmf_5
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setCmf5(String cmf5) {
        this.cmf5 = cmf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.date_1
     *
     * @return the value of t_core_sys_test.date_1
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public Date getDate1() {
        return date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.date_1
     *
     * @param date1 the value for t_core_sys_test.date_1
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setDate1(Date date1) {
        this.date1 = date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.date_2
     *
     * @return the value of t_core_sys_test.date_2
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public Date getDate2() {
        return date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.date_2
     *
     * @param date2 the value for t_core_sys_test.date_2
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setDate2(Date date2) {
        this.date2 = date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_sys_test.date_3
     *
     * @return the value of t_core_sys_test.date_3
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public Date getDate3() {
        return date3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_sys_test.date_3
     *
     * @param date3 the value for t_core_sys_test.date_3
     *
     * @mbg.generated Tue Nov 30 23:08:42 GMT+08:00 2021
     */
    public void setDate3(Date date3) {
        this.date3 = date3;
    }
}