server:
  port: 9456
  servlet:
    context-path: /aidata
spring:
  application:
    name: aidata_9456
  profiles:
    active: dev
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.105.215:3306/aidata?character_set_server=utf8mb4&serverTimezone=GMT%2B8
    username: root
    password: zs69894050481
  #    hikari:
  #      maximum-pool-size: 100
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
            threadPriority: 5
          jobListener:
            DefaultListener:
              class: com.zs.aidata.core.sys.mytest.job.DefaultListener
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zs.aidata
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
#logging:
#  config: classpath:config/log4j2-spring.xml
logging:
  config: classpath:config/logback-spring.xml

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://47.115.148.250:9456/aidata/eureka
  instance:
    instance-id: aidata9456
    hostname: 47.115.148.250
    prefer-ip-address: true #可以显示IP地址