spring:
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
            threadPriority: 2
          jobListener:
            DefaultListener:
              class: com.zs.aidata.core.sys.mytest.job.DefaultListener
